"""add back reviews

Revision ID: 0376b6635fe7
Revises: 1bcb60ae2a34
Create Date: 2025-02-03 11:57:36.006183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0376b6635fe7'
down_revision = '1bcb60ae2a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_rental_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_rental_id'], ['rentals.id'], name=op.f('fk_reviews_reviewed_rental_id_rentals')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
