"""remove amenities again

Revision ID: 1bcb60ae2a34
Revises: 3baa80fab5df
Create Date: 2025-02-03 11:54:56.623055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcb60ae2a34'
down_revision = '3baa80fab5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_amenities',
    sa.Column('rental_id', sa.INTEGER(), nullable=False),
    sa.Column('amenity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name='fk_rental_amenities_amenity_id_amenities'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name='fk_rental_amenities_rental_id_rentals'),
    sa.PrimaryKeyConstraint('rental_id', 'amenity_id')
    )
    # ### end Alembic commands ###
