"""add constra
int to daily rate. should be above 0

Revision ID: 1dd4efcb01f8
Revises: e442c9112c90
Create Date: 2025-02-05 16:46:17.781441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd4efcb01f8'
down_revision = 'e442c9112c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('daily_rate',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('daily_rate',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
