"""backtrack

Revision ID: 3715cae899e8
Revises: d6f06f72c0d0
Create Date: 2025-02-03 11:47:48.811473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3715cae899e8'
down_revision = 'd6f06f72c0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('amenities')
    op.drop_table('rental_amenities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_amenities',
    sa.Column('rental_id', sa.INTEGER(), nullable=False),
    sa.Column('amenity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name='fk_rental_amenities_amenity_id_amenities'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name='fk_rental_amenities_rental_id_rentals'),
    sa.PrimaryKeyConstraint('rental_id', 'amenity_id')
    )
    op.create_table('amenities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('reviewer_id', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_rental_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_rental_id'], ['rentals.id'], name='fk_reviews_reviewed_rental_id_rentals'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='fk_reviews_reviewer_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
