"""add unique in name in Rental

Revision ID: 48513df97df2
Revises: e18698854936
Create Date: 2025-02-05 16:04:40.606442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48513df97df2'
down_revision = 'e18698854936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rentals_name', ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rentals_name', type_='unique')

    # ### end Alembic commands ###
