"""add owner_id in rentals

Revision ID: d242f7aa1128
Revises: 08a25bf2e19f
Create Date: 2025-01-31 12:38:20.477407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd242f7aa1128'
down_revision = '08a25bf2e19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traveler_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_bookings_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookings_traveler_id_users'), 'users', ['traveler_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rentals_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rentals_owner_id_users'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_bookings_traveler_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bookings_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('traveler_id')

    # ### end Alembic commands ###
